### ISSUE TITLE
[GCE L7LB controller] watch cluster uid config map so updates propogate without restart

### ISSUE THREAD

**Issue by wittrock** [kubernetes/contrib#1362]
After upgrading two of my clusters in the same project from versions 1.2.5 to version 1.3 of kubernetes, their GCE objects are clobbering each other, and it seems to be because my manually-set `cluster-uid` got deleted during the upgrade. 

```
➜  ~ kubectl describe configMap --namespace kube-system
Name:       ingress-uid
Namespace:  kube-system
Labels:     <none>
Annotations:    <none>

Data
===
uid:    0 bytes
```

Even if I edit this configMap and add a cluster-uid, my GCE resources still clobber each other. For instance, all load balancers created by creating ingresses point to the same GCE instance group, called `k8s-ig`. Previously, they pointed to `k8s-ig--my-manually-set-uid`. 

Based on #680 by @bprashanth, it looks like new objects should be created with whatever is in that configMap first, but that's not happening. 

This is fixed if I spin up a new cluster and create a test ingress--those objects are properly namespaced.

Given that I can't fix the issue by editing ingress-uid manually, is there another workaround?

**Comment by bprashanth** [comment]
If this is on GCE you can restart your controller by ssh-ing into the master. 
Assuming this is on GKE, I can restart your controller (I also just mailed you).
Deleting the pod won't restart the actual container, since we're now running it as a static pod.

**Comment by bprashanth** [comment]
This is also a bug because we should allow modification of cluster-uid by watching the configmap, we currently don't do so, which is why the restart is necessary. Thanks for the report.

**Comment by bprashanth** [comment]
I think this was fixed, feel free to reopen if that's not the case

**Comment by bprashanth** [comment]
No, that doesn't make sense. The issue isn't fixed, a single occurrance of the issue was worked around. reopening.

**Comment by DanielHeckrath** [comment]
@bprashanth I can confirm this issue is still present after updating my cluster from 1.2.4 to 1.3.5 on GKE. Controller also doesn't seem to pick up recently set uid because of the static pod issue you mentioned. How can I restart the controller on GKE so that it's uses the updated id?

**Comment by bprashanth** [comment]
@DanielHeckrath sorry for the hassle, please do: https://groups.google.com/forum/#!searchin/kubernetes-users/ingress%7Csort:relevance/kubernetes-users/QpsRZcaVmks/ltJYsdr7BQAJ
A fix has been checked in but it will only be in 1.3.6.
