### ISSUE TITLE
How is this possible?

### ISSUE THREAD

**Issue by bojanv55** [kubernetes/contrib#2930]
I installed curl in the elector image. Running 3 replicas.

```
# curl -sSk -H "Authorization: Bearer $TOKEN" \
      https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_PORT_443_TCP_PORT/api/v1/namespaces/default/endpoints/example>
{
  "kind": "Endpoints",
  "apiVersion": "v1",
  "metadata": {
    "name": "example",
    "namespace": "default",
    "selfLink": "/api/v1/namespaces/default/endpoints/example",
    "uid": "7dfccbfa-85b6-11e8-b2ab-08002702cbca",
    "resourceVersion": "3202186",
    "creationTimestamp": "2018-07-12T09:32:27Z",
    "annotations": {
      "control-plane.alpha.kubernetes.io/leader": "{\"holderIdentity\":\"aspectcaffleader-84d5769dbd-wq9cf\",\"leaseDurationSeconds\":10,\"acquireTime\":\"2018-07-12T09:34:59Z\",\"renewTime\":\"2018-07-12T10:13:39Z\",\"leaderTransitions\":0}"
    }
  }
}# curl localhost:4040
{"name":"aspectcaffleader-59df7bb4fc-8slv8"}#
```

Master that is in the endpoint is not the same as the one reported by elector locally?

Update is done OK when master is deleted and new MASTER has OK name, but name of the master returned by STANDBY nodes is not correct.

**Comment by trajakovic** [comment]
can confirm @bojanv55 issue:


```
kubectl get pods|grep leader-ele                                                                                                                     
leader-elector-78dc57584b-6sltq                               1/1       Running   0          11m
leader-elector-78dc57584b-qc8z4                               1/1       Running   0          4m
leader-elector-78dc57584b-xrdpb                               1/1       Running   0          13m
```

```
kubectl get endpoints example -o yaml                                                                                                                
apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    control-plane.alpha.kubernetes.io/leader: '{"holderIdentity":"leader-elector-78dc57584b-6sltq","leaseDurationSeconds":10,"acquireTime":"2018-07-28T13:37:38Z","renewTime":"2018-07-28T13:40:46Z","leaderTransitions":0}'
  creationTimestamp: 2018-07-28T13:28:11Z
  name: example
  namespace: staging
  resourceVersion: "18868468"
  selfLink: /api/v1/namespaces/staging/endpoints/example
  uid: 12d99a29-926a-11e8-8f24-0a96b526afb2
subsets: []
```

While curling other instances (than real leader):

```
curl http://localhost:8001/api/v1/proxy/namespaces/staging/pods/leader-elector-78dc57584b-qc8z4:4040/                                               
{"name":"leader-elector-78dc57584b-z68dz"}%
```


If I ask real leader:

```
curl http://localhost:8001/api/v1/proxy/namespaces/staging/pods/leader-elector-78dc57584b-6sltq:4040/                                              
{"name":"leader-elector-78dc57584b-6sltq"}
```

He's the only one who's aware of himself, while others have wrong/dead/killed pod/leader name


---

P.S.
This demo was started with:

```
kubectl run leader-elector --image=k8s.gcr.io/leader-elector:0.5 --replicas=3 --serviceaccount=leader-elector-example -- --election=example --election-namespace=staging --http=0.0.0.0:4040
```

while serviceaccount was bound to:
```
kubectl get role leader-elector -o yaml                                                                                                            
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: 2018-07-28T13:03:56Z
  name: leader-elector
  namespace: staging
  resourceVersion: "18860555"
  selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/staging/roles/leader-elector
  uid: af4e73b7-9266-11e8-8f24-0a96b526afb2
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
```

**Comment by fredrik-jansson-se** [comment]
I also ran into this and reported this: https://github.com/kubernetes/contrib/issues/2933

I'll try to mark mine as a duplicate.

**Comment by fredrik-jansson-se** [comment]
I pull the latest contrib code, and rebuilt the container manually... cannot reproduce anymore, so my guess is that this has been fixed, but no new container pushed.

**Comment by u05rav** [comment]
This is still an issue worth the gcr image.  fredrik's image works fine.  Any chance of getting a new official image?

**Comment by piushs** [comment]
@brendandburns @mikedanese Can one of you please make this image official? The current image gcr.io/google_containers/leader-elector:0.5  has problems, where it shows the old leader, when we send http requests to know the leader to pods that are not leader (as described in this issue).

**Comment by cog-qlik** [comment]
/remove-lifecycle stale

The problem is still here, as most users pointed out. Can you please solve this at the root, publishing a fixed docker image?
