### ISSUE TITLE
add-ons don't get installed properly

### ISSUE THREAD

**Issue by rakesh-k** [kubernetes/contrib#886]
Must say up front - I am trying the install on redhat. Having said that after correcting the paths little bit I am able to get the cluster up and running. But for some reason the add-ons don't get installed even though I see the activities  related to grafana, heapster, and influxdb in the log file. 

This is what I get after the install:

```
[rakeshk@cd3labvdapp002 ~]$ kubectl cluster-info
Kubernetes master is running at http://localhost:8080
```

From the log:
```

2016-05-02 16:22:51,989 p=18914 u=rakeshk |  task path: /home/rakeshk/contrib/ansible/roles/kubernetes-addons/tasks/cluster-monitoring.yml:11
2016-05-02 16:22:53,512 p=18914 u=rakeshk |  ok: [cd3labvdapp002 -> localhost] => (item=grafana-service.yaml) => {"changed": false, "checksum_dest": "487a140bd7f826b16eec34c6cd293c5e9a04f774", "checksum_src": "487a140bd7f826b16eec34c6cd293c5e9a04f774", "dest": "/tmp/kubernetes/addons/cluster-monitoring/grafana-service.yaml.j2", "gid": 1012, "group": "rakeshk", "item": "grafana-service.yaml", "md5sum": "8b492d5ee6bf197684d9c3cedd86201d", "mode": "0664", "msg": "OK (431 bytes)", "owner": "rakeshk", "size": 431, "src": "/tmp/tmpsHRowM", "state": "file", "uid": 1012, "url": "https://raw.githubusercontent.com/GoogleCloudPlatform/kubernetes/master/cluster/addons/cluster-monitoring/influxdb/grafana-service.yaml"}
2016-05-02 16:22:53,548 p=18914 u=rakeshk |  ok: [cd3labvdapp002 -> localhost] => (item=heapster-controller.yaml) => {"changed": false, "checksum_dest": "d65ae026a787914518a8b9227b5e16c024d11fb8", "checksum_src": "680ed4f1282025987cad1ff8bebef9bf1c62ae8e", "dest": "/tmp/kubernetes/addons/cluster-monitoring/heapster-controller.yaml.j2", "gid": 1012, "group": "rakeshk", "item": "heapster-controller.yaml", "md5sum": "e0b52e80a2bb0e8ec74b925412305629", "mode": "0664", "msg": "OK (3688 bytes)", "owner": "rakeshk", "size": 3688, "src": "/tmp/tmpQpRU3R", "state": "file", "uid": 1012, "url": "https://raw.githubusercontent.com/GoogleCloudPlatform/kubernetes/master/cluster/addons/cluster-monitoring/influxdb/heapster-controller.yaml"}
2016-05-02 16:22:53,583 p=18914 u=rakeshk |  ok: [cd3labvdapp002 -> localhost] => (item=heapster-service.yaml) => {"changed": false, "checksum_dest": "fa6a6611afc134933df625660e5044f5a485d077", "checksum_src": "fa6a6611afc134933df625660e5044f5a485d077", "dest": "/tmp/kubernetes/addons/cluster-monitoring/heapster-service.yaml.j2", "gid": 1012, "group": "rakeshk", "item": "heapster-service.yaml", "md5sum": "f455a4c445fb61865170494cbc0d872e", "mode": "0664", "msg": "OK (258 bytes)", "owner": "rakeshk", "size": 258, "src": "/tmp/tmpjYya6a", "state": "file", "uid": 1012, "url": "https://raw.githubusercontent.com/GoogleCloudPlatform/kubernetes/master/cluster/addons/cluster-monitoring/influxdb/heapster-service.yaml"}
2016-05-02 16:22:53,616 p=18914 u=rakeshk |  ok: [cd3labvdapp002 -> localhost] => (item=influxdb-grafana-controller.yaml) => {"changed": false, "checksum_dest": "2c8d5bbd5117cbaab7926d9bb04976c2c8c781b1", "checksum_src": "2c8d5bbd5117cbaab7926d9bb04976c2c8c781b1", "dest": "/tmp/kubernetes/addons/cluster-monitoring/influxdb-grafana-controller.yaml.j2", "gid": 1012, "group": "rakeshk", "item": "influxdb-grafana-controller.yaml", "md5sum": "24e5ba5b0d0bc75ec64728f8aed3e7d7", "mode": "0664", "msg": "OK (2423 bytes)", "owner": "rakeshk", "size": 2423, "src": "/tmp/tmp7_aGKc", "state": "file", "uid": 1012, "url": "https://raw.githubusercontent.com/GoogleCloudPlatform/kubernetes/master/cluster/addons/cluster-monitoring/influxdb/influxdb-grafana-controller.yaml"}
2016-05-02 16:22:53,650 p=18914 u=rakeshk |  ok: [cd3labvdapp002 -> localhost] => (item=influxdb-service.yaml) => {"changed": false, "checksum_dest": "bc359e21f8779fe54a15c4ca4616f4d90f2d6bca", "checksum_src": "bc359e21f8779fe54a15c4ca4616f4d90f2d6bca", "dest": "/tmp/kubernetes/addons/cluster-monitoring/influxdb-service.yaml.j2", "gid": 1012, "group": "rakeshk", "item": "influxdb-service.yaml", "md5sum": "1d195f93019f20ffece7a0d5c177f06a", "mode": "0664", "msg": "OK (351 bytes)", "owner": "rakeshk", "size": 351, "src": "/tmp/tmpFcdZ2E", "state": "file", "uid": 1012, "url": "https://raw.githubusercontent.com/GoogleCloudPlatform/kubernetes/master/cluster/addons/cluster-monitoring/influxdb/influxdb-service.yaml"}

```
...
```

2016-05-02 16:22:56,194 p=18914 u=rakeshk |  TASK [kubernetes-addons : MONITORING | Install template from converted saltfile] ***
2016-05-02 16:22:56,195 p=18914 u=rakeshk |  task path: /home/rakeshk/contrib/ansible/roles/kubernetes-addons/tasks/cluster-monitoring.yml:55
2016-05-02 16:22:59,649 p=18914 u=rakeshk |  ok: [cd3labvdapp002] => (item=grafana-service.yaml) => {"changed": false, "gid": 0, "group": "root", "item": "grafana-service.yaml", "mode": "0755", "owner": "root", "path": "/etc/kubernetes/addons/cluster-monitoring/grafana-service.yaml", "size": 431, "state": "file", "uid": 0}
2016-05-02 16:22:59,685 p=18914 u=rakeshk |  ok: [cd3labvdapp002] => (item=heapster-controller.yaml) => {"changed": false, "gid": 0, "group": "root", "item": "heapster-controller.yaml", "mode": "0755", "owner": "root", "path": "/etc/kubernetes/addons/cluster-monitoring/heapster-controller.yaml", "size": 3119, "state": "file", "uid": 0}
2016-05-02 16:22:59,723 p=18914 u=rakeshk |  ok: [cd3labvdapp002] => (item=heapster-service.yaml) => {"changed": false, "gid": 0, "group": "root", "item": "heapster-service.yaml", "mode": "0755", "owner": "root", "path": "/etc/kubernetes/addons/cluster-monitoring/heapster-service.yaml", "size": 258, "state": "file", "uid": 0}
2016-05-02 16:22:59,764 p=18914 u=rakeshk |  ok: [cd3labvdapp002] => (item=influxdb-grafana-controller.yaml) => {"changed": false, "gid": 0, "group": "root", "item": "influxdb-grafana-controller.yaml", "mode": "0755", "owner": "root", "path": "/etc/kubernetes/addons/cluster-monitoring/influxdb-grafana-controller.yaml", "size": 2423, "state": "file", "uid": 0}
2016-05-02 16:22:59,799 p=18914 u=rakeshk |  ok: [cd3labvdapp002] => (item=influxdb-service.yaml) => {"changed": false, "gid": 0, "group": "root", "item": "influxdb-service.yaml", "mode": "0755", "owner": "root", "path": "/etc/kubernetes/addons/cluster-monitoring/influxdb-service.yaml", "size": 351, "state": "file", "uid": 0}
```

**Comment by rakesh-k** [comment]
```
[rakeshk@cd3labvdapp002 system]$ sudo systemctl status kube-addons
● kube-addons.service - Kubernetes Addon Object Manager
   Loaded: loaded (/etc/systemd/system/kube-addons.service; enabled; vendor preset: disabled)
   Active: active (running) since Sat 2016-04-30 15:58:29 EDT; 2 days ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
 Main PID: 13835 (kube-addons.sh)
   Memory: 2.6M
   CGroup: /system.slice/kube-addons.service
           ├─13835 /bin/bash /usr/libexec/kubernetes/kube-addons.sh
           ├─30211 /bin/bash /usr/libexec/kubernetes/kube-addons.sh
           └─30212 /usr/bin/kubectl get --namespace=kube-system serviceaccount default -o go-template={{with index .secrets 0}}{{.name}}{{end}}

May 03 10:53:30 cd3labvdapp002 kube-addons.sh[13835]: error: output format "go-template={{with index .secrets 0}}{{.name}}{{end}}" not recognized
May 03 10:53:31 cd3labvdapp002 kube-addons.sh[13835]: error: output format "go-template={{with index .secrets 0}}{{.name}}{{end}}" not recognized
```

**Comment by bprashanth** [comment]
Does the kube system namespace exist?
```
 Failed creating a mirror pod "fluentd-elasticsearch-cd3labvdapp002_kube-system": Pod "fluentd-elasticsearch-cd3labvdapp002" is forbidden: Namespace kube-system does not exist
```

**Comment by rakesh-k** [comment]
As per the log it does not and I checked it too. The addons should create
it before installing themselves, I suppose. I am using the contrib repo's
ansible script.

**Comment by gouyang** [comment]
is the kubelet service up?

**Comment by rakesh-k** [comment]
[rakeshk@cd3labvdapp002 group_vars]$ kubectl describe node cd3labvdapp002
Name:                   cd3labvdapp002
Labels:                 kubernetes.io/hostname=cd3labvdapp002
CreationTimestamp:      Sun, 01 May 2016 22:30:59 -0400
Conditions:
  Type          Status  LastHeartbeatTime
LastTransitionTime
Reason                                  Message
  Ready         True    Tue, 03 May 2016 23:09:05 -0400         Mon, 02 May
2016 16:24:28 -0400         kubelet is posting ready status
Addresses:      172.27.36.101
Capacity:
 memory:        8008352Ki
 pods:          40
 cpu:           2
Version:
 Kernel Version:                3.10.0-229.el7.x86_64
 OS Image:                      Red Hat Enterprise Linux
 Container Runtime Version:     docker://1.8.2-el7
 Kubelet Version:               v1.0.3.34+b9a88a7d0e357b
 Kube-Proxy Version:            v1.0.3.34+b9a88a7d0e357b
ExternalID:                     cd3labvdapp002
Pods:                           (2 in total)
  Namespace                     Name
  default                       nginx-qi9zm
  default                       nginx-scy94
No events.

**Comment by rakesh-k** [comment]
```
[rakeshk@cd3labvdapp002 group_vars]$ kubectl describe node cd3labvdapp002
Name:                   cd3labvdapp002
Labels:                 kubernetes.io/hostname=cd3labvdapp002
CreationTimestamp:      Sun, 01 May 2016 22:30:59 -0400
Conditions:
  Type          Status  LastHeartbeatTime                       LastTransitionTime                      Reason                                  Message
  Ready         True    Tue, 03 May 2016 23:09:05 -0400         Mon, 02 May 2016 16:24:28 -0400         kubelet is posting ready status
Addresses:      172.27.36.101
Capacity:
 memory:        8008352Ki
 pods:          40
 cpu:           2
Version:
 Kernel Version:                3.10.0-229.el7.x86_64
 OS Image:                      Red Hat Enterprise Linux
 Container Runtime Version:     docker://1.8.2-el7
 Kubelet Version:               v1.0.3.34+b9a88a7d0e357b
 Kube-Proxy Version:            v1.0.3.34+b9a88a7d0e357b
ExternalID:                     cd3labvdapp002
Pods:                           (2 in total)
  Namespace                     Name
  default                       nginx-qi9zm
  default                       nginx-scy94
No events.
```

**Comment by gouyang** [comment]
There is a problem that kubelet service is not restarted because "state=started" is missing in  [1].
I could see that namespace=kube-system is not created when kubelet is not running.

https://github.com/kubernetes/contrib/blob/master/ansible/roles/node/tasks/main.yml#L62

**Comment by rakesh-k** [comment]
@gouyang you are right - here is the service log (for some reason the service shows as enabled):

```
[rakeshk@cd3labvdapp002 kubernetes]$ sudo systemctl status kubelet
● kubelet.service - Kubernetes Kubelet Server
   Loaded: loaded (/usr/lib/systemd/system/kubelet.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2016-05-02 16:24:25 EDT; 1 day 7h ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
 Main PID: 21002 (kubelet)
   Memory: 52.1M
   CGroup: /system.slice/kubelet.service
           └─21002 /usr/bin/kubelet --logtostderr=true --v=0 --api-servers=https://cd3labvdapp002:443 --address=0.0.0.0 --hostname-override=cd3labvdapp002 --allow-privileged=true --kubeconfig=/etc/kubernetes/kubelet.kub...

May 04 00:18:41 cd3labvdapp002 kubelet[21002]: E0504 00:18:41.921333   21002 kubelet.go:1260] Failed creating a mirror pod "fluentd-elasticsearch-cd3labvdapp002_kube-system": Pod "fluentd-elasticsearch-cd... does not exist
May 04 00:18:51 cd3labvdapp002 kubelet[21002]: E0504 00:18:51.947640   21002 kubelet.go:1260] Failed creating a mirror pod "fluentd-elasticsearch-cd3labvdapp002_kube-system": Pod "fluentd-elasticsearch-cd... does not exist
May 04 00:19:01 cd3labvdapp002 kubelet[21002]: E0504 00:19:01.938249   21002 kubelet.go:1260] Failed creating a mirror pod "fluentd-elasticsearch-cd3labvdapp002_kube-system": Pod "fluentd-elasticsearch-cd... does not exist
May 04 00:19:11 cd3labvdapp002 kubelet[21002]: E0504 00:19:11.943662   21002 kubelet.go:1260] Failed creating a mirror pod "fluentd-elasticsearch-cd3labvdapp002_kube-system": Pod "fluentd-elasticsearch-cd... does not exist
May 04 00:19:21 cd3labvdapp002 kubelet[21002]: E0504 00:19:21.961166   21002 kubelet.go:1260] Failed creating a mirror pod "fluentd-elasticsearch-cd3labvdapp002_kube-system": Pod "fluentd-elasticsearch-cd... does not exist
May 04 00:19:31 cd3labvdapp002 kubelet[21002]: E0504 00:19:31.964801   21002 kubelet.go:1260] Failed creating a mirror pod "fluentd-elasticsearch-cd3labvdapp002_kube-system": Pod "fluentd-elasticsearch-cd... does not exist
May 04 00:19:41 cd3labvdapp002 kubelet[21002]: E0504 00:19:41.966213   21002 kubelet.go:1260] Failed creating a mirror pod "fluentd-elasticsearch-cd3labvdapp002_kube-system": Pod "fluentd-elasticsearch-cd... does not exist
May 04 00:19:51 cd3labvdapp002 kubelet[21002]: E0504 00:19:51.981382   21002 kubelet.go:1260] Failed creating a mirror pod "fluentd-elasticsearch-cd3labvdapp002_kube-system": Pod "fluentd-elasticsearch-cd... does not exist
May 04 00:20:02 cd3labvdapp002 kubelet[21002]: E0504 00:20:02.004098   21002 kubelet.go:1260] Failed creating a mirror pod "fluentd-elasticsearch-cd3labvdapp002_kube-system": Pod "fluentd-elasticsearch-cd... does not exist
May 04 00:20:11 cd3labvdapp002 kubelet[21002]: E0504 00:20:11.997205   21002 kubelet.go:1260] Failed creating a mirror pod "fluentd-elasticsearch-cd3labvdapp002_kube-system": Pod "fluentd-elasticsearch-cd... does not exist
Hint: Some lines were ellipsized, use -l to show in full.
```

But the docker containers have fluentd-elasticsearch running:

```
[rakeshk@cd3labvdapp002 kubernetes]$ docker ps
CONTAINER ID        IMAGE                                                 COMMAND                  CREATED             STATUS              PORTS               NAMES
ec4a6def71b7        nginx                                                 "nginx -g 'daemon off"   31 hours ago        Up 31 hours                             k8s_nginx.9a41f625_nginx-scy94_default_a2af7a52-1084-11e6-967c-0050563c011d_976b8716
f49c3ea9da02        nginx                                                 "nginx -g 'daemon off"   31 hours ago        Up 31 hours                             k8s_nginx.9a41f625_nginx-qi9zm_default_9fc6ec6f-1084-11e6-967c-0050563c011d_6c323271
20857b4cb7a1        gcr.io/google_containers/pause:0.8.0                  "/pause"                 31 hours ago        Up 31 hours                             k8s_POD.e4cc795_nginx-scy94_default_a2af7a52-1084-11e6-967c-0050563c011d_40248c36
fa55a751b87f        gcr.io/google_containers/pause:0.8.0                  "/pause"                 31 hours ago        Up 31 hours                             k8s_POD.e4cc795_nginx-qi9zm_default_9fc6ec6f-1084-11e6-967c-0050563c011d_f7067a63
ecc923ff6a17        gcr.io/google_containers/fluentd-elasticsearch:1.15   "td-agent"               31 hours ago        Up 31 hours                             k8s_fluentd-elasticsearch.cb72b3a7_fluentd-elasticsearch-cd3labvdapp002_kube-system_53df16aa2e7689fc1b6b812b9e9772bf_6d8dbf8e
2323c076f835        gcr.io/google_containers/pause:0.8.0                  "/pause"                 31 hours ago        Up 31 hours                             k8s_POD.e4cc795_fluentd-elasticsearch-cd3labvdapp002_kube-system_53df16aa2e7689fc1b6b812b9e9772bf_e13c647f
```

**Comment by gouyang** [comment]
There are mainly two problems:

1. kube-system namespace is not created, which cause addons cannot be not created.
https://github.com/kubernetes/kubernetes/issues/23973  is fixed for Atomic host.

and I opened this
https://github.com/kubernetes/contrib/pull/895

2. skydns is not created because of error like below

# kubectl create -f skydns-rc.yaml 
error validating "skydns-rc.yaml": error validating data: [found invalid field failureThreshold for v1.Probe, found invalid field successThreshold for v1.Probe]; if you choose to ignore these errors, turn validation off with --validate=false

you need to run it manually. 
`$ kubectl create -f /etc/kubernetes/addons/dns/skydns-rc.yaml --validate=false`

**Comment by rakesh-k** [comment]
@gouyang I made the fix locally and reran the playbook but still have the same issue. For some reason the kube-system namespace is not getting created. Kubelet service has the same log as above. Here is logfile snippet:
```
2016-05-04 08:18:06,420 p=1147 u=rakeshk |  TASK [node : Enable kubelet] ***************************************************
2016-05-04 08:18:06,420 p=1147 u=rakeshk |  task path: /home/rakeshk/contrib/ansible/roles/node/tasks/main.yml:61
2016-05-04 08:18:06,883 p=1147 u=rakeshk |  ok: [cd3labvdapp005] => {"changed": false, "enabled": true, "invocation": {"module_args": {"arguments": "", "enabled": true, "name": "kubelet", "pattern": null, "runlevel": "default", "sleep": null, "state": "started"}, "module_name": "service"}, "name": "kubelet", "state": "started"}
2016-05-04 08:18:06,898 p=1147 u=rakeshk |  ok: [cd3labvdapp004] => {"changed": false, "enabled": true, "invocation": {"module_args": {"arguments": "", "enabled": true, "name": "kubelet", "pattern": null, "runlevel": "default", "sleep": null, "state": "started"}, "module_name": "service"}, "name": "kubelet", "state": "started"}
2016-05-04 08:18:06,942 p=1147 u=rakeshk |  ok: [cd3labvdapp003] => {"changed": false, "enabled": true, "invocation": {"module_args": {"arguments": "", "enabled": true, "name": "kubelet", "pattern": null, "runlevel": "default", "sleep": null, "state": "started"}, "module_name": "service"}, "name": "kubelet", "state": "started"}
2016-05-04 08:18:07,080 p=1147 u=rakeshk |  ok: [cd3labvdapp002] => {"changed": false, "enabled": true, "invocation": {"module_args": {"arguments": "", "enabled": true, "name": "kubelet", "pattern": null, "runlevel": "default", "sleep": null, "state": "started"}, "module_name": "service"}, "name": "kubelet", "state": "started"}
```


When I try to run the command you asked to run manually I get the following:

```
[rakeshk@cd3labvdapp002 ansible]$ kubectl create -f /etc/kubernetes/addons/dns/skydns-rc.yaml --validate=false
Error from server: error when creating "/etc/kubernetes/addons/dns/skydns-rc.yaml": ReplicationController "kube-dns-v11" is forbidden: Namespace kube-system does not exist
```

**Comment by rakesh-k** [comment]
I manually created the kube-system namespace and then loaded other add-ons. Wonder why the namespace is not loaded by the script automatically? The /var/log/messages has these repeated messages:

`kube-addons.sh: error: output format "go-template={{with index .secrets 0}}{{.name}}{{end}}" not recognized`

I can not find reference to these in any of the scripts so it must be part of downloaded programs. Is there something wrong with compilation upstream?

**Comment by gouyang** [comment]
`kube-addons.sh: error: output format "go-template={{with index .secrets 0}}{{.name}}{{end}}" not recognized`

Could not see this error here:
`# kubectl get serviceaccount default -o go-template="{{with index .secrets 0}}{{.name}}{{end}}"
default-token-fcvuv`

What kubernetes version are you using?

**Comment by rakesh-k** [comment]
This is what I get:

```
[~]$ kubectl get serviceaccount default -o go-template="{{with index .secrets 0}}{{.name}}{{end}}"
error: output format "go-template={{with index .secrets 0}}{{.name}}{{end}}" not recognized
```

```
[ ~]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"0.3", GitVersion:"v1.0.3.34+b9a88a7d0e357b", GitCommit:"b9a88a7d0e357be2174011dd2b127038c6ea8929", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"0.3", GitVersion:"v1.0.3.34+b9a88a7d0e357b", GitCommit:"b9a88a7d0e357be2174011dd2b127038c6ea8929", GitTreeState:"clean"}

```

**Comment by gouyang** [comment]
I think you should at least upgrade to kube 1.2 version, it has been release for a while.

And the namespace problem should be gone in next release, the dns addon should still need create manually on that release.

**Comment by rakesh-k** [comment]
I think it was installed through the ansible script itself. Do I need to tweak the script to upgrade?

**Comment by rakesh-k** [comment]
Is there a way to tear down the entire install and install a fresh?

**Comment by gouyang** [comment]
> I think it was installed through the ansible script itself. Do I need to tweak the script to upgrade?

no, the script is already doing that for you. You need to check whether you have subscribe the Red Hat related pool and enabled that repo.

**Comment by gouyang** [comment]
> Is there a way to tear down the entire install and install a fresh?

I'm doing it like below:

```
systemctl stop kube-proxy
systemctl stop kubelet
systemctl stop kube-apiserver
systemctl stop kube-controller-manager
systemctl stop kube-scheduler
systemctl stop kube-addons

systemctl stop docker
systemctl start docker

etcdctl rm --recursive /registry
```

**Comment by rakesh-k** [comment]
redhat repo has 1.0.3. How can I get the 1.2 rpm?

**Comment by rakesh-k** [comment]
@gouyang can you send me the redhat pool so that I can confirm. I can only see the 1.0.3 rpm.

**Comment by gouyang** [comment]
The pool should be different for each subscriber, do you enabled the `rhel-7-server-extras-rpms`?

**Comment by rakesh-k** [comment]
I have that repo but I could  only see version 1.0.3 for kubernetes.

I tried localInstall as well - but that did not seem to work for some
reason. The document is vague about the package location etc. I will check
with redhat rep to find out more on the subscription part.

**Comment by rakesh-k** [comment]
@gouyang I did get the version 1.2 of kubernetes and did a fresh install. This is the error that I get out of `journalctl -xe`

`May 06 15:41:36 cd3labvdapp002 kube-addons.sh[24297]: Error from server: serviceaccounts "default" not found`

**Comment by gouyang** [comment]
@rakesh-k Good to know you have kube 1.2 now, but this version still have the namespace problem, it's issue https://github.com/kubernetes/contrib/issues/777. Wait for next update from Red Hat, this problem is fixed, see https://bugzilla.redhat.com/show_bug.cgi?id=1327335.

You can change "apply" to "create" in kube-addons.sh to fix the namespace issue.
The skydns still need to create manually in next release.

**Comment by rakesh-k** [comment]
@gouyang I changed the **kube-addons.sh** file to use create. (I had already created the namespace by simply executing the kubectl create command) I see 2 issues now:

1. the script assumes that it is being run for the first time and thus the '`kube-system`' namespace does not exist. But if it does then it does not know how to handle it and keeps on looping for a while.

2. The script expects **/etc/kubernetes/admission-controls** but that does not exist. Which ansible role/task is supposed to create that?

**Comment by ingvagabund** [comment]
```
rpm -qa | grep kubernetes
kubernetes-client-1.2.0-0.11.git738b760.el7.x86_64
kubernetes-master-1.2.0-0.11.git738b760.el7.x86_64
kubernetes-node-1.2.0-0.11.git738b760.el7.x86_64
kubernetes-debuginfo-1.2.0-0.6.alpha1.git8632732.el7.x86_64
```

Installing the addons from the kubernetes/contrib master HEAD.

```
kubectl cluster-info
Kubernetes master is running at http://localhost:8080
Elasticsearch is running at http://localhost:8080/api/v1/proxy/namespaces/kube-system/services/elasticsearch-logging
Heapster is running at http://localhost:8080/api/v1/proxy/namespaces/kube-system/services/heapster
Kibana is running at http://localhost:8080/api/v1/proxy/namespaces/kube-system/services/kibana-logging
KubeDNS is running at http://localhost:8080/api/v1/proxy/namespaces/kube-system/services/kube-dns
Grafana is running at http://localhost:8080/api/v1/proxy/namespaces/kube-system/services/monitoring-grafana
InfluxDB is running at http://localhost:8080/api/v1/proxy/namespaces/kube-system/services/monitoring-influxdb
```

```
kubectl get ns
NAME          STATUS    AGE
default       Active    271d
kube-system   Active    71d
```

**Comment by ingvagabund** [comment]
@gouyang can you confirm? My steps:

1. provision one node (or VM)
1. install the latest rpms from brew
1. clone contrib repository
1. use this inventory file
   ```
   [masters]
localhost ansible_connection=local

[nodes]
localhost ansible_connection=local

[etcd]
localhost ansible_connection=local
   ```

1. update ``ansible/roles/master/tasks/main.yml`` removing everything up to the first task, i.e. keep
   ```
---
- include: coreos.yml
  when: is_coreos
```
The reason is to skip the part where the kube is installed via ansible scripts.

1. run ``ansible-playbook -i inventory.txt --tags addons ./cluster.yml`` under ansible directory

**Comment by ingvagabund** [comment]
It works even if you skip step ``5``. I just takes a little longer and you can get:

```
TASK: [master | Open firewalld port for apiserver] **************************** 
failed: [localhost] => {"failed": true, "parsed": false}
BECOME-SUCCESS-htxvrlcmqglyvwmlyicygqxgorjwmcbt
failed=True msg='failed to connect to the firewalld daemon'
```

Anyway, the ansible roles should be rewritten to be able to just run the minimal subset of roles to install kube-addons on system with kubernetes already installed on.

**Comment by ingvagabund** [comment]
For better refinement of the roles: https://github.com/kubernetes/contrib/issues/1280

**Comment by gouyang** [comment]
@ingvagabund Your steps are right.

**Comment by gouyang** [comment]
@rakesh-k All problem are fixed, could you please take a look at this again?

**Comment by ingvagabund** [comment]
@rakesh-k I am closing the issue for now. If you find the add-ons still does not work, please open a new issue.
